name: CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy Code to GCE
      run: |
        # Copy files to GCE instance
        gcloud compute scp --recurse \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --zone=${{ secrets.GCE_ZONE }} \
          ./* ${{ secrets.GCE_INSTANCE }}:~/plurk-hotwater-bot/

    - name: Setup and Run Bot
      run: |
        gcloud compute ssh ${{ secrets.GCE_INSTANCE }} \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --zone=${{ secrets.GCE_ZONE }} \
          --command="
            cd ~/plurk-hotwater-bot
            
            # Kill existing screen sessions
            pkill screen 2>/dev/null || true
            
            # Create .env file with secrets
            cat > .env << EOF
            PLURK_CONSUMER_KEY=${{ secrets.PLURK_CONSUMER_KEY }}
            PLURK_CONSUMER_SECRET=${{ secrets.PLURK_CONSUMER_SECRET }}
            PLURK_ACCESS_TOKEN=${{ secrets.PLURK_ACCESS_TOKEN }}
            PLURK_ACCESS_TOKEN_SECRET=${{ secrets.PLURK_ACCESS_TOKEN_SECRET }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            EOF
            
            # Setup Python environment
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-venv screen
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            
            # Start bot in screen session
            screen -dmS plurk_bot_screen bash -c 'source venv/bin/activate && python src/bot.py'
            
            echo 'Bot deployment completed successfully!'
          "