name: CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up SSH Key
      shell: bash
      run: |
        echo "${{ secrets.EC2_KEY }}" > ~/plurk-bot.pem
        chmod 400 ~/plurk-bot.pem

    - name: Deploy Code
      shell: bash
      run: |
        scp -i ~/plurk-bot.pem -r * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/plurk-hotwater-bot
        ssh -i ~/plurk-bot.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/plurk-hotwater-bot
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          screen -dmS plurk_bot_screen bash -c 'source venv/bin/activate && python src/bot.py'
        EOF